apiVersion: v1
kind: Service
metadata:
  name: apigateway
  labels:
    app.kubernetes.io/name: apigateway
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: apigateway
  ports:
    - name: http
      port: 8000
      targetPort: 8000
-----
apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway
  labels:
    app.kubernetes.io/name: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: apigateway
  template:
    metadata:
      labels:
        app.kubernetes.io/name: apigateway
    spec:
      containers:
        - name: apigateway
          image: apigateway:1.0.0
          imagePullPolicy: IfNotPresent
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: k8s
            - name: SPRING_CLOUD_CONFIG_URI
              value: http://config-service.default.svc.cluster.local:8888
          command: ["java"]
          args:
            - "-Dspring.profiles.active=${SPRING_PROFILES_ACTIVE}"
            - "-Dlogstash.url=${LOGSTASH_URL}"
            - "-jar"
            - "/usr/app/apigateway.jar"
          ports:
            - containerPort: 8000
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8000
            initialDelaySeconds: 45
            periodSeconds: 20
          volumeMounts:
            - name: messages
              mountPath: /usr/app/msa-attach-volume/messages
      volumes:
        - name: messages
          emptyDir: {}
